### ISSUE TITLE
Creating a form

### ISSUE THREAD

**Issue by Kachev** [Kachev/Capston-Project#1]
## Value Proposition

- As a User
- I want a list of forms
- in order to fill in

## Description

![Image](https://user-images.githubusercontent.com/93873677/227921775-ffe46e3b-9562-4919-91ba-debdcb10eb2b.png)

​

## Acceptance Criteria

- [x] The title is displayed above the rides list and is not fixed
- [x] The "Arbeitszeiten" card has text input fields for Text and number input fields for Time and one for Date.
- [x] The card ( Kunde ) has a input fields whit "Name" , "Familienname" and "Adresse"
- [x] After pressing the Submit button ( Fertigstellen ), the completed form is saved and displayed on page 2.
- [x] Creating page 2.

## Tasks

- [x] Create branch
- [x] add component/card Arbeitszeit/
- [x] add component / card Kunde/
- [x] add component/button for submitting the form "Fertigstellen"/
- [x] create new page
- [x] create a Card list for the completed form on page 2
- [x] Create dummy data
- [x] Global Styles
- [x] Write tests

**Comment by PReichetanz** [comment]
Nice work, Hristo!

Just one thing to consider while implementing this story: I guess you don't need different Card components for "Arbeitszeiten" and "Kunde", but both parts should be inside the same form, but maybe in different `<fieldset>` tags.
