### ISSUE TITLE
Creating a new Card for the Form

### ISSUE THREAD

**Issue by Kachev** [Kachev/Capston-Project#2]
## Value Proposition

- As a User
- I want to be able to add what materials, tools and machines are used.

## Description

![Image](https://user-images.githubusercontent.com/93873677/227949645-2cdfa984-a837-4119-8708-be1820f27c4e.png)

## Acceptance Criteria

- [x] The "Materialien, Maschinen und Geräte" card has 4 Columns with drop-down menu for " Materialien, Maschinen und Geräte, Entsorgung" and  fields for number input. The Column "Pflanzen" has input fields for text and numbers.
- [x] The cards has a " + " buttons, witch sets a new drop-down menus or fields for entering text and numbers.
- [x] After pressing the Submit button ( Fertigstellen ), the completed form is saved and displayed on page 2.
- [x] Page 2 has a " + " button to create a new Form
- [x] The list is scrollable

## Tasks

- [x] new branch
- [x] add component/card "Materialien, Maschinen und Gärete"/
- [x] add component/drop-down menu for the card/
- [x] add component/text and number inputs for the card /
- [x] add component/buttons for a new drop-down menus or text and numbers input/
- [x] add component/ "+" button on page 2 to create a new Form/
- [x] write tests

**Comment by Gblur** [comment]
Can you submit these informations after filling out all these froms?
Can you describe which input fields you need?

For tasks I would additionally add a point like "add a function for updating the previous state of the fields"

**Comment by PReichetanz** [comment]
Hi Hristo,

nice work!

I am not sure where the data is displayed after submitting the form. Could you please add this information to your wireframe / acceptance criteria?

**Comment by alexWaligorski** [comment]
Hey Hristo, this looks great! Whant an amazing project! 

I would recommend to follow the suggestions by @Gblur and:

- be more specific about the structure of the cards. How many? For what kind of equipment, how many columns per card? Which card has a drop down? Which card/column is a textinput?

- which fields are optional and which required?

- Also: After pressing the submit button only a short/small version of the form (date and customer name) is displayed in your scetch. You will probably need a new component for that.

- And what happens when 2 Forms have been filled out? how does the "after submit screen" look like then? Will the 2 or more forms be displayed in a list?



I hope these hints are helpful to you.
Have a nice weekend!

**Comment by Kachev** [comment]
Thanks so much for all your tips and ideas! I hope it is now better and comprehensibly described.

**Comment by PReichetanz** [comment]
Hi Hristo,

nice work here! I see that you want to the user to add all this information all at once, but in your scribble, most of the information is not visible after submitting the form.
~~So my suggestion is to divide the story into two: left and right screen is your first story, and the middle screen is the second: when implementing this advanced part of the form, you can think about where to display all the information (or save it for now).~~

~~The reason is that in the current state, the user adds information into a form, but does not have any value from submitting it (except the date and name of the client).~~

Update (because I now better understand what you are doing here): You should display all submitted information on the page (below the date and the name of the client) so that the user can check what he has submitted.
It does not have to look fancy, but you will create value for the user with this.

**Comment by Kachev** [comment]
Hi @PReichetanz ,

Can you please explain to me what you meant? I didn't understand you.

**Comment by Kachev** [comment]
@PReichetanz
 If I understood you correctly, too little information is displayed on the 2nd page when the report is saved.
For the next US I have planned preview windows, edit button and delete.

**Comment by PReichetanz** [comment]
Nice work! The only thing missing is where and how the information is displayed after clicking the submit button. And can I enter a second set of data which is saved (and displayed) as well?

**Comment by Gblur** [comment]
As I already metnioned.
The numbers in the input fields can be negative.
The break input should be better a number than a date I think.
And maybe but not necessary for now using regex pattern for input validation.
But all in all its really cool.
