### ISSUE TITLE
Creating a new card for the Form

### ISSUE THREAD

**Issue by Kachev** [Kachev/Capston-Project#3]
## Value Proposition

As a user
I want to able to add a work report
in order to filling and saving it.
​

## Description

![Image](https://user-images.githubusercontent.com/93873677/227970556-e2fe848b-dd3c-46f4-bf72-2e62b2ef5427.png)

## Acceptance Criteria
- [ ] The card "Arbeitsbeschreibung" has a drop-down menu with a job description and one text input field (Textarea) to further describe the job, which is not available in the drop-down menu.
- [ ] The card "Arbeitsbeschreibung" has a "+" button, witch sets a new drop-down menu with job description.
- [ ] After clicking the Submit button ( Fertigstellen ), the completed form is saved and displayed on page 2.
- [ ] After clicking  the "+" button on page 2, a new form appears to be filled out (screen 1).

## Tasks
- [x] create new branch
- [x] add component/ new card "Arbeitsbeschreibung"/
- [x] create element/ a drop-down menu
- [x] create element/  button to sets a new drop-down menu
- [x] create element/textarea
- [x] write tests

**Comment by PReichetanz** [comment]
Hi Hristo,

a really good start for your user story! 🎉

💬 Let's discuss some issues which came to my mind while reading:

## Value Proposition
The third part is missing: "in order to [...]"

## Acceptance Criteria
I would add something like this:
- If I click the "+" button on page 2, a new form appears to be filled out (screen 1).

## Tasks
- a drop-down, button and textarea are (in most cases) no components on its own; but maybe this is something you are going to decide while implementing it.
