### ISSUE TITLE
Edit and Delete button

### ISSUE THREAD

**Issue by Kachev** [Kachev/Capston-Project#9]
## Value Proposition

As a user
I want to be able to update saved reports or delete.

## Description

![Image](https://user-images.githubusercontent.com/93873677/233372507-89aa1bd2-c70b-46a3-bcdc-8c4933410deb.png)

​

## Acceptance Criteria

- [ ] Delete button "Löschen" to deleting the work report
- [ ] After clicking the delete button "Löschen", the user must confirm his wish

      
## Tasks

- [ ] new branch
- [ ] add components/Delete button
- [ ] Implement the functionality to delete the post
- [ ] write test

**Comment by actyvystom** [comment]
A good start for this one!
As you are mentioning the delete and update functionality in your task list, you should also enhance your acceptance criteria. Some questions to consider:
- what happens _exactly_ when the user clicks the edit button?
- what happens when clicking the delete button (will the saved work report be deleted instantly or is there a kind of dialogue to verify deletion)?
